### ISSUE TITLE
format-lint-check errors

### ISSUE THREAD

**Issue by JunHerng** [s-fifteen-instruments/pyS15#2]
Format-lint-check on github fails for unknown reason.

![image](https://user-images.githubusercontent.com/52197879/170959135-60e57d5b-d0a3-4911-9781-ea5625e6508a.png)

Tests for all four python versions: 3.6, 3.7, 3.8, 3.9 fail at Run Tests step, returning error code 1. This is the extended log of the Run Tests step.

```
Run pre-commit run --all-files
  pre-commit run --all-files
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.6.15/x64/lib
[INFO] Initializing environment for https://github.com/pycqa/isort.
[INFO] Initializing environment for https://github.com/python/black.git.
[INFO] Initializing environment for https://github.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/python/black.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /home/runner/work/pyS15/pyS15/S15lib/apps/powermeter_app.py

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted S15lib/instruments/spdc_driver.py
reformatted S15lib/instruments/usb_counter_fpga.py
All done! ✨ 🍰 ✨
[2](https://github.com/s-fifteen-instruments/pyS15/runs/6652156073?check_suite_focus=true#step:5:2) files reformatted, 1[4](https://github.com/s-fifteen-instruments/pyS15/runs/6652156073?check_suite_focus=true#step:5:4) files left unchanged.

flake[8](https://github.com/s-fifteen-instruments/pyS15/runs/6652156073?check_suite_focus=true#step:5:9)...................................................................Passed
mypy.....................................................................Passed
Error: Process completed with exit code 1.
```

**Comment by JunHerng** [comment]
Looks like an error on Github's side. Somehow they have a wrong function call to one of their internal packages, shown below from the error messages in builds 3.7 and up:

```
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repolyz4n6sj/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/.cache/pre-commit/repolyz4n6sj/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1282, in patched_main
    patch_click()
  File "/home/runner/.cache/pre-commit/repolyz4n6sj/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1268, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repolyz4n6sj/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```
